# Generated by Django 5.2.8 on 2025-12-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='email',
        ),
    ]
