# Generated by Django 5.2.8 on 2025-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Intermediate+', 'Intermediate+'), ('Good', 'Good'), ('Advanced', 'Advanced'), ('Growing', 'Growing'), ('Comfortable', 'Comfortable')], max_length=50)),
                ('percentage', models.PositiveIntegerField(default=50)),
                ('tags', models.TextField(help_text='Comma-separated values')),
            ],
        ),
    ]
